### PR TITLE
Make State::panic unsafe

### PR DESCRIPTION
**Pull request by cjcole**
$ cargo --version && rustc --version
cargo 0.0.1-pre-nightly (e689383 2015-03-16) (built 2015-03-16)
rustc 1.0.0-nightly (ecf8c64e1 2015-03-21) (built 2015-03-21)

### CODE REVIEW

**Comment by kballard** [comment]
What's the motivating reason for this change?

**Comment by cjcole** [comment]
Unless I'm mistaken, it doesn't build with the latest Rust nightly otherwise.

BTW, thanks for the library. I use it pretty extensively (without problems so far).

**Comment by kballard** [comment]
Travis has been failing for the past couple of days with a curious error about an empty `-L` flag. I haven't looked into it yet. I admit I haven't built locally for a few days, but I hadn't had an error with this before. I'll check today (and see if I can't figure out what's going on with Travis).

**Comment by cjcole** [comment]
Ok. I built locally and it failed. After the change in this pull request, it worked. Verification is always welcome, though.

I noticed the Travis complaint, too. No idea.

**Comment by kballard** [comment]
Looks like rust-lang/rust#23452 made safe fns no longer subtypes of unsafe fns.

**Comment by kballard** [comment]
I ended up making a larger change that encompasses this one. Committed as 73b912f13c198ff5945ad16ae37568192d10c37b. Thanks!

**Comment by cjcole** [comment]
Great, thanks.

**Pull request closed without merging**
